# Generated by Django 3.1.4 on 2021-07-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netto', '0016_auto_20201129_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_series',
            field=models.CharField(blank=True, choices=[('Cisco Ethernet 2000 Switches', 'Cisco Ethernet 2000 Switches'), ('Cisco Router 2900 Series', 'Cisco Router 2900 Series')], max_length=255),
        ),
    ]
