# Generated by Django 3.1.4 on 2021-07-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netto', '0018_auto_20210717_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_series',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
    ]
